### ISSUE TITLE
[크롤링] 일만개 레시피를 크롤링해서 제목, 재료, 재료수량을 분리한다.

### ISSUE THREAD

**Issue by sokcuri** [woowahan-techcamp/3team_osgd#1]
**ruby**와 **node.js**를 이용해 일만개 레시피 사이트 크롤링을 진행해보자

## 사용 라이브러리 버전
* ruby 2.3.3
* node.js 8.2.1

할일 목록
- [x] 타이틀, 이름, 주소, 사진, 재료 리스트 분리
- [ ] 예외 처리

**Comment by ghost** [comment]
http://www.10000recipe.com/recipe/6874029 의 경우
[재료]
오이지 1개, 매실청 3.5T, 불린 실미역 조금, 청·홍고추 1/4개, 얼음 3알
[양념]
현미식초 1T, 설탕 1t, 깨 1/3t, 고춧가루 살짝, 시원한 생수 300cc
원래는 스페이스바로 split후에 first는 재료, last는 유닛으로 하려했으나, 불린 실미역 조금, 시원한 생수 같은 경우 문제가 발생한다. 이런 경우가 얼마나 있을지는 조사해야할듯!

**Comment by ghost** [comment]
일만 레시피 >> 해먹남녀 이동
