### ISSUE TITLE
메인 페이지 화면 세부 구현

### ISSUE THREAD

**Issue by asfaca** [woowahan-techcamp/3team_osgd#13]
* HTML
- [x] url 입력창의 돋보기 아이콘 누르면 결과를 submit하기

- [x] 시즌메뉴 슬라이드 구현하기 위해 DOM구조 개편

- [x] 메인 헤더 그림 페이드 인, 아웃 하기 위해 DOM구조 개편

- [x] url입력창 폼쓰지 않는 구조로 바꾸기

* javascript
- [x] 메인 헤드의 url 입력창 포커스시 placeholder clear

- [x] 메인 헤드의 이미지 페이드 인, 아웃 구현

- <del>추천 메뉴에 호버로 그림 위에 레시피 사이트 이름 띄워주기</del>

- [x] 시즌메뉴 슬라이드 구현

- [x] ajax 받아서 추천메뉴, 시즌메뉴 컨텐츠 채워넣기

**Comment by chsbru** [comment]
오늘 원래 일정으로는 메인 그림 페이드인/페이드아웃을 구현해야 했어야 하나 못함..

**Comment by chsbru** [comment]
호버로 레시피 사이트를 띄워주는 것은 다음에 한다
