### ISSUE TITLE
[크롤링] 음식 재료 DB 구축

### ISSUE THREAD

**Issue by sokcuri** [woowahan-techcamp/3team_osgd#2]
## 이유 1
1만개의 레시피 사이트에서 정규화된 재료를 제공하는 경우도 있으나, 때때로 정규화되지 않은 (한줄로 된) 재료를 제공하기도 한다.

```markdown
[재료]
돼지갈비 약 1200g, 감자 작은것 2개, 새송이버섯 1개, 무 조금, 통마늘 한줌, 대파 한줌
[양념]
간장 9Ts, 설탕 4Ts, 다진대파 3Ts, 다진마늘 1.5Ts, 매실액 1Ts, 참기름 1Ts, 깨 조금, 후추 약간, 물 3컵(600ml)
```

이 때 음식 재료를 제대로 파싱하기 위해 재료 DB를 구축해야 한다

## 이유 2
1만개의 레시피 사이트에서는 유사 재료 리스트를 가지고 있다. 현실적으로 모든 재료를 구비할 수는 없기에 유사 재료 (또는 대체 재료)가 필요한데, 이 리스트가 필요하므로 재료 DB를 구축해야 한다.

## 할일 목록
- [ ] 10개의 레시피에 대한 재료 상품 데이터를 엑셀화(이미지, 용량, 가격 등등)
- [ ] 재료 데이터 db

**Comment by ghost** [comment]
재료의 or처리 어떻게할까!
 
다양한 유닛..;;
1g
주먹
넉넉히
1그릇
적당량
치즈
슬라이스
500원동전
2개
반병
1봉지
적당량

**Comment by chsbru** [comment]
여러 유닛은 적당한 값으로 치환시키는것이 좋을것같아. 예를 들어 1주먹 -- 300g라던가.

**Comment by ghost** [comment]
해먹남녀의 경우 재료가 정규화 되어있다~
해먹남녀의 재료를 모두 크롤링하여 서버 디비에 넣어두었다.
유닛 문제의 경우, 제공하는 상품하나를 기본적으로 구매하게했으며,
구매자는 리스트에서 본인의 수량을 설정한다.
